.TH LOGFACTOR5 1 "08 April 2013" "log4j-1.2.17" "User commands"

.SH NAME
logfactor5 \- GUI tool for viewing logging events

.SH SYNOPSIS
.BR logfactor5

.SH DESCRIPTION

LogFactor5 is a Swing based GUI tool for viewing logging events that
leverages the power of Log4j logging framework and provides developers
with a sophisticated, feature-rich, logging interface for managing log
messages.

LogFactor5 seamlessly plugs into Log4j and provides developers with an
alternate destination for outputting messages.
